import { useCallback, useState } from 'react'
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { BarChart3, Building2, ChevronDown, FileSpreadsheet, LayoutDashboard, Menu, Settings, Trophy, UploadCloud } from 'lucide-react'
import { NavLink, Navigate, Route, Routes } from 'react-router-dom'
import { useDropzone } from 'react-dropzone'
import { parseWorkbook } from './lib/excel/importer'
import type { ImportPreview } from './types/domain'

const queryClient = new QueryClient()
const nav = [{ to: '/', label: 'Visão geral', icon: LayoutDashboard }, { to: '/equipamentos', label: 'Equipamentos', icon: Building2 }, { to: '/rankings', label: 'Rankings', icon: Trophy }, { to: '/importacoes', label: 'Importações', icon: FileSpreadsheet }, { to: '/definicoes', label: 'Definições', icon: Settings }]
const money = new Intl.NumberFormat('pt-AO', { style: 'currency', currency: 'AOA', maximumFractionDigits: 0 })

function Shell() {
  const [open, setOpen] = useState(false)
  return <div className="min-h-screen bg-[#f4f7f5] lg:grid lg:grid-cols-[260px_1fr]">
    <aside className={`${open ? 'block' : 'hidden'} fixed inset-y-0 z-20 w-64 bg-[#102b22] p-5 text-white lg:static lg:block lg:w-auto`}>
      <div className="mb-9 flex items-center gap-3"><div className="rounded-xl bg-emerald-400 p-2 text-[#102b22]"><BarChart3 /></div><div><b>ATM Insight</b><p className="m-0 text-xs text-emerald-100">Análise de desempenho</p></div></div>
      <nav className="space-y-1">{nav.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} end={to === '/'} onClick={() => setOpen(false)} className={({ isActive }) => `flex items-center gap-3 rounded-xl px-3 py-3 text-sm ${isActive ? 'bg-white/14 font-semibold text-white' : 'text-slate-300 hover:bg-white/8'}`}><Icon size={19} />{label}</NavLink>)}</nav>
      <div className="absolute bottom-5 left-5 right-5 rounded-xl border border-white/10 bg-white/5 p-3 text-xs text-slate-300"><b className="text-white">Dados reservados</b><p className="mb-0">Acesso sujeito a autenticação e perfil.</p></div>
    </aside>
    <main><header className="flex h-18 items-center justify-between border-b border-slate-200 bg-white px-5 lg:px-8"><button className="lg:hidden" onClick={() => setOpen(!open)} aria-label="Abrir menu"><Menu /></button><div className="hidden text-sm text-slate-500 sm:block">Última actualização <b className="text-slate-800">Julho de 2026</b></div><button className="flex items-center gap-3 rounded-xl border border-slate-200 px-3 py-2 text-left"><div className="grid h-8 w-8 place-items-center rounded-full bg-emerald-100 font-bold text-emerald-800">DA</div><span className="hidden text-sm sm:block"><b>Diogo Almeida</b><small className="block text-slate-500">Analista</small></span><ChevronDown size={16} /></button></header><div className="p-5 lg:p-8"><Routes><Route path="/" element={<Overview />} /><Route path="/equipamentos" element={<Equipment />} /><Route path="/rankings" element={<Base title="Rankings" text="Compare os melhores e piores desempenhos por indicador." />} /><Route path="/importacoes" element={<Imports />} /><Route path="/definicoes" element={<Base title="Definições" text="Clientes, limites de alerta e perfis de utilizador." />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></div></main>
  </div>
}

function Heading({ title, text }: { title: string; text: string }) { return <div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><h1 className="m-0 text-2xl font-bold text-slate-900">{title}</h1><p className="mt-1 text-sm text-slate-500">{text}</p></div><div className="flex gap-2"><select className="rounded-xl border border-slate-200 bg-white px-4 py-2"><option>BCI</option><option>BKEVE</option></select><select className="rounded-xl border border-slate-200 bg-white px-4 py-2"><option>Julho 2026</option></select></div></div> }
function Overview() { const stats = [['Total de ATMs', '128', '+4 este mês'], ['Transacções', '1 284 520', '+8,4% vs. Jun'], ['Montante transaccionado', money.format(14820000000), '+6,2% vs. Jun'], ['Downtime médio', '3,8%', '-0,7 p.p. vs. Jun'], ['ATMs em alerta', '12', '3 críticos']]; return <><Heading title="Visão geral" text="Uma leitura clara do desempenho mensal da rede." /><div className="mb-4 rounded-xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-800"><b>Modo demonstração:</b> os indicadores abaixo são fictícios e serão substituídos quando ligar o Supabase.</div><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{stats.map(([label, value, trend], i) => <article className="card" key={label}><p className="label">{label}</p><strong className="mt-3 block text-2xl text-slate-900">{value}</strong><p className={`mb-0 text-xs ${i === 4 ? 'text-orange-600' : 'text-emerald-700'}`}>{trend}</p></article>)}</section><section className="mt-5 grid gap-5 xl:grid-cols-3"><article className="card xl:col-span-2"><h2 className="mt-0 text-base">Evolução mensal</h2><div className="mt-8 flex h-52 items-end gap-3">{[55,62,58,70,76,84,91].map((n, i) => <div className="flex flex-1 flex-col items-center gap-2" key={i}><div className="w-full rounded-t-lg bg-emerald-600/90" style={{height:`${n}%`}} /><small className="text-slate-400">{['Jan','Fev','Mar','Abr','Mai','Jun','Jul'][i]}</small></div>)}</div></article><article className="card"><h2 className="mt-0 text-base">Atenção necessária</h2>{[['ATM 0048','Downtime 14,2%','Crítico'],['ATM 0103','Transacções -42%','Alto'],['ATM 0081','8 dias activos','Médio']].map(x=><div className="border-b border-slate-100 py-3" key={x[0]}><b className="text-sm">{x[0]}</b><p className="my-1 text-xs text-slate-500">{x[1]}</p><span className="text-xs font-semibold text-orange-600">{x[2]}</span></div>)}</article></section></> }
function Equipment() { return <><Heading title="Equipamentos" text="Consulte indicadores, tendências e alertas por terminal." /><div className="card overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="text-xs uppercase text-slate-500"><tr>{['Terminal','Cliente','Transacções','Montante','Downtime','Tendência','Alerta'].map(h=><th className="pb-4" key={h}>{h}</th>)}</tr></thead><tbody>{[['ATM-0048','BCI','8 420','Kz 94,2 M','14,2%','↓ 31%','Crítico'],['ATM-0081','BCI','12 780','Kz 151,8 M','2,1%','↑ 8%','Normal'],['ATM-0103','BCI','6 340','Kz 70,4 M','4,8%','↓ 42%','Alto']].map(r=><tr className="border-t border-slate-100" key={r[0]}>{r.map((v,i)=><td className={`py-4 ${i===0?'font-semibold':''}`} key={i}>{v}</td>)}</tr>)}</tbody></table><p className="text-xs text-sky-700">Dados de demonstração.</p></div></> }
function Imports() { const [preview, setPreview] = useState<ImportPreview | null>(null); const [busy,setBusy]=useState(false); const onDrop=useCallback(async(files:File[])=>{const file=files[0]; if(!file)return; setBusy(true); setPreview(parseWorkbook(await file.arrayBuffer(),file.name)); setBusy(false)},[]); const drop=useDropzone({onDrop,accept:{'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet':['.xlsx']},multiple:false}); return <><Heading title="Importações" text="Valide o relatório antes de guardar qualquer dado." /><div {...drop.getRootProps()} className={`card cursor-pointer border-2 border-dashed py-12 text-center ${drop.isDragActive?'border-emerald-500 bg-emerald-50':'border-slate-300'}`}><input {...drop.getInputProps()} /><UploadCloud className="mx-auto text-emerald-700" size={42}/><h2 className="mb-1 text-lg">{busy?'A analisar…':'Arraste o ficheiro Excel para aqui'}</h2><p className="text-sm text-slate-500">ou clique para seleccionar um ficheiro .xlsx</p></div>{preview&&<section className="mt-5 grid gap-5 lg:grid-cols-3"><article className="card"><p className="label">Detecção automática</p><dl className="text-sm"><dt className="text-slate-500">Cliente</dt><dd className="font-semibold">{preview.detected.client??'Não detectado'}</dd><dt className="text-slate-500">Período</dt><dd>{preview.detected.period??'Não detectado'}</dd><dt className="text-slate-500">Folha principal</dt><dd>{preview.mainSheet??'Não encontrada'}</dd><dt className="text-slate-500">Linhas</dt><dd>{preview.totalRows}</dd></dl></article><article className="card lg:col-span-2"><p className="label">Validação</p>{preview.issues.length===0?<p className="text-emerald-700">Nenhum problema encontrado.</p>:preview.issues.map((issue,i)=><p key={i} className={`rounded-lg p-2 text-sm ${issue.severity==='error'?'bg-red-50 text-red-700':'bg-amber-50 text-amber-800'}`}><b>{issue.code}</b> — {issue.message}</p>)}</article></section>}</> }
function Base({title,text}:{title:string;text:string}) { return <><Heading title={title} text={text}/><div className="card"><p className="text-sm text-slate-500">Estrutura preparada para a próxima fase.</p></div></> }
export default function App(){return <QueryClientProvider client={queryClient}><Shell/></QueryClientProvider>}
